description="前回Commitとの差分を取得して、コメントを自動生成した上でコミットします。"
prompt = """
すべて日本語で実行してください。
Gitの前回Commitとの差分を基に、コミットメッセージを自動生成してコミットまで実行してください。

以下の手順に従ってください：

1. `git status && git diff HEAD && git log -n 3` を実行して、変更内容を確認します。
2. 変更があったファイルや追跡されていないファイルがあれば、`git add`コマンドでステージングします。なければ次の手順に進みます。
    このとき変更箇所にあまりよろしくない書き方をしているコードがあればこの手順はここで終了し、どの部分がだめでどう治すべきかをユーザーに伝えて終了してください
3. 削除されたファイルがあれば、`git rm`コマンドで削除します。なければ次の手順に進みます。
4. 過去のコミットログを参考に、Conventional Commitsの規約に沿った日本語のコミットメッセージを提案します。
5. コミットが完了したら、`git status`で状態を確認します。
6. コミットが正常に完了し、作業ディレクトリがクリーンな状態であることを確認します。

Git関連のタスクには、シェルツールを組み合わせてGitコマンド（`git`）を使用してください。
"""